#ifndef LIST_HPP
#define LIST_HPP
#include <string>
#include <vector>

namespace CTRPluginFramework
{
    static const std::vector<std::string> listToggle = {
        "はい",
        "いいえ"};

    static const std::vector<std::string> listFixKeyboard{
        "定型文",
        "キーボード"};

    static const std::vector<std::string> list1to10Magnification{
        "1倍",
        "2倍",
        "3倍",
        "4倍",
        "5倍",
        "6倍",
        "7倍",
        "8倍",
        "9倍",
        "10倍"};

    static const std::vector<std::string> listSkinColor{
        "赤色",
        "橙色",
        "黄色",
        "黄緑",
        "緑色",
        "緑水",
        "水色",
        "水青",
        "青色",
        "紫色",
        "紫桃",
        "白色",
        "灰色",
        "黒色"};

    static const std::vector<std::string> listAmuletType{
        "表示無し",
        "兵士の護石",
        "闘士の護石",
        "騎士の護石",
        "城塞の護石",
        "女王の護石",
        "王の護石",
        "龍の護石"};

    static const std::vector<std::string> listAmuletSkill{
        "スキル無し",
        "毒",
        "麻痺",
        "睡眠",
        "気絶",
        "聴覚保護",
        "風圧",
        "耐震",
        "だるま",
        "耐暑",
        "耐寒",
        "寒冷適応",
        "炎熱適応",
        "盗み無効",
        "対防御DOWN",
        "狂撃耐性",
        "細菌学",
        "裂傷",
        "攻撃",
        "防御",
        "体力",
        "火耐性",
        "水耐性",
        "雷耐性",
        "氷耐性",
        "龍耐性",
        "属性耐性",
        "火属性攻撃",
        "水属性攻撃",
        "雷属性攻撃",
        "氷属性攻撃",
        "龍属性攻撃",
        "属性攻撃",
        "特殊攻撃",
        "研ぎ師",
        "匠",
        "斬れ味",
        "剣術",
        "研磨術",
        "鈍器",
        "抜刀会心",
        "抜刀滅気",
        "納刀",
        "装填速度",
        "反動",
        "精密射撃",
        "通常弾強化",
        "貫通弾強化",
        "散弾強化",
        "重撃弾強化",
        "通常弾追加",
        "貫通弾追加",
        "散弾追加",
        "榴弾追加",
        "拡散弾追加",
        "毒瓶追加",
        "麻痺瓶追加",
        "睡眠瓶追加",
        "強撃瓶追加",
        "属強瓶追加",
        "接撃瓶追加",
        "滅気瓶追加",
        "爆破瓶追加",
        "速射",
        "射法",
        "装填数",
        "変則射撃",
        "弾薬節約",
        "達人",
        "痛撃",
        "連撃",
        "特殊会心",
        "属性会心",
        "会心強化",
        "溜め短縮",
        "スタミナ",
        "体術",
        "気力回復",
        "回避性能",
        "回避距離",
        "泡沫",
        "ガード性能",
        "ガード強化",
        "KO",
        "滅気攻撃",
        "笛",
        "砲術",
        "重撃",
        "爆弾強化",
        "本気",
        "闘魂",
        "無傷",
        "チャンス",
        "底力",
        "逆境",
        "逆上",
        "窮地",
        "根性",
        "気配",
        "采配",
        "号令",
        "乗り",
        "跳躍",
        "無心",
        "千里眼",
        "観察眼",
        "狩人",
        "運搬",
        "加護",
        "英雄の盾",
        "回復量",
        "回復速度",
        "効果持続",
        "広域",
        "腹減り",
        "食いしん坊",
        "食事",
        "節食",
        "肉食",
        "茸食",
        "野草知識",
        "調合成功率",
        "調合数",
        "高速設置",
        "採取",
        "ハチミツ",
        "護石王",
        "気まぐれ",
        "運気",
        "剥ぎ取り",
        "捕獲",
        "ベルナ",
        "ココット",
        "ポッケ",
        "ユクモ",
        "紅兜",
        "大雪主",
        "矛砕",
        "岩穿",
        "紫毒姫",
        "宝纏",
        "白疾風",
        "隻眼",
        "黒炎王",
        "金雷公",
        "荒鉤爪",
        "燼滅刃",
        "北辰納豆流",
        "胴系統倍加"};

    static const std::vector<std::string> listAmuletSlot{
        "0スロット",
        "1スロット",
        "2スロット",
        "3スロット"};

    static const std::vector<std::string> list1to4Player{
        "P1",
        "P2",
        "P3",
        "P4"};

    static const std::vector<std::string> listRegion{
        "日本",
        "ヨーロッパ"};

    static const std::vector<std::string> listSpecialTicket{
        "紅兜アオアシラ",
        "大雪主ウルクスス",
        "矛砕ダイミョウザザミ",
        "紫毒姫リオレイア",
        "岩穿テツカブラ",
        "白疾風ナルガクルガ",
        "宝纏ウラガンキン",
        "隻眼イャンガルルガ",
        "黒炎王リオレウス",
        "金雷公ジンオウガ",
        "荒鉤爪ティガレックス",
        "燼滅刃ディノバルド"};

    static const std::vector<std::string> listQuestClear{
        "クエストクリア",
        "クエスト失敗"};

    static const std::vector<std::string> listViewingAngle{
        "デフォルト",
        "視野角変更"};

    static const std::vector<std::string> listVillage{
        "ベルナ村",
        "ココット村",
        "ポッケ村",
        "ユクモ村"};

    static const std::vector<std::string> listRoomService{
        "ルームサービス",
        "キャラバンの看板娘",
        "モガの村の看板娘",
        "タンジアの港の看板娘",
        "ぽかぽか島の管理人"};

    static const std::vector<std::string> listGuildCardChangeGroup{
        "称号",
        "クリア回数",
        "すれ違い回数",
        "友好度",
        "背景",
        "ポーズ",
        "武器使用回数",
        "プレイ時間",
        "モンスター狩猟記録"};

    static const std::vector<std::string> listGuildCardChangeTitle{
        "称号1",
        "称号2",
        "称号3"};

    static const std::vector<std::string> listGuildCardChangeClearValue{
        "村",
        "集会所下位",
        "集会所上位",
        "特殊許可クエスト",
        "闘技大会"};

    static const std::vector<std::string> listGuildCardChangeWeaponUseGroup{
        "村",
        "集会所",
        "闘技大会",
        "全てカンスト"};

    static const std::vector<std::string> listGuildCardChangeWeaponUseType{
        "大剣",
        "片手剣",
        "ハンマー",
        "ランス",
        "ヘビィボウガン",
        "ライトボウガン",
        "太刀",
        "スラッシュアックス",
        "ガンランス",
        "弓",
        "双剣",
        "狩猟笛",
        "操虫棍",
        "チャージアックス",
        "ニャンター"};

    static const std::vector<std::string> listGuildCardChangeMonsterHuntingGroup{
        "狩猟数",
        "捕獲数",
        "どちらもカンスト"};

    static const std::vector<std::string> listGuildCardChangeMonsterHuntingBigSmall{
        "大型モンスター",
        "小型モンスター"};

    static const std::vector<std::string> listGuildCardChangeMonsterHuntingBig{
        "リオレイア",
        "リオレイア希少種",
        "紫毒姫リオレイア",
        "リオレウス",
        "リオレウス希少種",
        "黒炎王リオレウス",
        "フルフル",
        "イャンクック"
        "ゲリョス",
        "ガノトトス",
        "キリン",
        "ドスランポス",
        "ドスゲネポス",
        "ドスイーオス",
        "ドスガレオス",
        "イャンガルルガ",
        "隻眼イャンガルルガ",
        "ダイミョウザザミ",
        "矛砕ダイミョウザザミ",
        "ショウグンギザミ",
        "ドドブランゴ",
        "ラージャン",
        "激昂したラージャン",
        "クシャルダオラ",
        "オオナズチ",
        "テオ・テスカトル",
        "ドスファンゴ",
        "ティガレックス",
        "荒鉤爪ティガレックス",
        "アカムトルム",
        "ヴォルガノス",
        "ナルガクルガ",
        "白疾風ナルガクルガ",
        "ウカムルバス",
        "イビルジョー",
        "怒り喰らうイビルジョー",
        "ウラガンキン",
        "宝纏ウラガンキン",
        "ラギアクルス",
        "ロアルドロス",
        "アグナコトル",
        "アルバトリオン",
        "ドボルベルク",
        "ハプルボッカ",
        "ジンオウガ",
        "金雷公ジンオウガ"
        "アマツマガツチ",
        "アオアシラ",
        "紅兜アオアシラ",
        "ウルクスス",
        "大雪主ウルクスス",
        "ラングロトラ",
        "ブラキディオス",
        "ケチャワチャ",
        "テツカブラ",
        "岩穿テツカブラ",
        "ザボアザギル",
        "ガララアジャラ",
        "ゲネル・セルタス",
        "ゴア・マガラ",
        "シャガルマガラ",
        "アルセルタス",
        "セルレギオス",
        "ホロロホルル",
        "ディノバルド",
        "燼滅刃ディノバルド",
        "ライゼクス",
        "タマミツネ",
        "ガムート",
        "オストガロア",
        "ドスマッカォ"};

    static const std::vector<std::string> listGuildCardChangeMonsterHuntingSmall{
        "アプトノス",
        "アプケロス",
        "ケルビ",
        "モス",
        "カンタロス",
        "ランゴスタ",
        "アイルー",
        "メラルー",
        "ランポス",
        "ゲネポス",
        "イーオス",
        "ガレオス",
        "ブルファンゴ",
        "ポポ",
        "ギアノス",
        "ガウシカ",
        "ガブラス",
        "ヤオザミ",
        "ガミザミ",
        "ブランゴ",
        "リノプロス",
        "ブナハブラ",
        "オルタロス",
        "ジャギィ",
        "ジャギィノス",
        "ルドロス",
        "ウロコトル",
        "ズワロポス",
        "ガーグァ",
        "スクアギル",
        "クンチュウ",
        "マッカォ",
        "リモセトス",
        "ムーファ"};

    static const std::vector<std::string> listItemBoxEdit{
        "アイテムを入れる[1400種]",
        "アイテムを入れる[548種]",
        "全アイテム99個",
        "全アイテム消去"};

    static const std::vector<std::string> listStageSelect{
        "0段階目",
        "1段階目",
        "2段階目",
        "3段階目",
        "4段階目"};

    static const std::vector<std::string> listAllQuestClearSelect{
        "クエスト全クリア",
        "クエスト全未クリア"};

    static const std::vector<std::string> listFenyClothes{
        "ルンルンベル",
        "愛しのマドモワゼル",
        "召しませ姫林檎",
        "常夏りリゾート"};

    static const std::vector<std::string> listPugyClothes{
        "思い出ストライプ",
        "夢追いアミーゴ",
        "はだかの王様",
        "魅惑のピンク",
        "緑と黒の衝撃",
        "眠りを誘う白",
        "ドリームスター",
        "天使のレオタード",
        "カエルのマーチ",
        "ひよっこアフロ",
        "ブラックハニー",
        "純真クレナイ",
        "おシノビ裝束",
        "マフモフウォーマー",
        "ブンブンビー",
        "ファンキーアフロ",
        "いやされムーチョ",
        "さすらい道中",
        "チューボー見習い",
        "あやかし装束",
        "あまくちピンク",
        "なき虫ベイビー",
        "なついろ恋浴衣",
        "モスのきもち",
        "ルドロスウォーマー",
        "ウーパールンバ",
        "イビルのきもち",
        "ドスのきもち",
        "ハートの女王様",
        "パンプキンナイト",
        "キラキラ★ナイト"};

    static const std::vector<std::string> listInsectType{
        "なし",
        "クルドローン",
        "アルマスタッグ",
        "ガシルドーレ",
        "カゼキリバネ",
        "モナークブルスタッグ",
        "レジナヴォランテ",
        "ドゥンクラーブ",
        "ウカドゥーレ",
        "オオシナト",
        "シナトモドキ",
        "エルドラーン",
        "マルドローン",
        "ザミールビートル",
        "ハルキータ",
        "ガルーヘル",
        "ケーニヒゴアビートル",
        "フィルカーノ",
        "ドルンキータ",
        "アルジョアーニャ",
        "メイヴァーチル",
        "ヴァンリエール",
        "アルジャーロン",
        "光のルフ",
        "バレットホーク",
        "とら",
        "表示無し"};

    static const std::vector<std::string> listVoiceType{
        "TYPE 1",
        "TYPE 2",
        "TYPE 3",
        "TYPE 4",
        "TYPE 5",
        "TYPE 6",
        "TYPE 7",
        "TYPE 8",
        "TYPE 9",
        "TYPE 10",
        "TYPE 11",
        "TYPE 12",
        "TYPE 13",
        "TYPE 14",
        "TYPE 15",
        "TYPE 16",
        "TYPE 17",
        "TYPE 18",
        "TYPE 19",
        "TYPE 20"};

    static const std::vector<std::string> listEyeType{
        "茶色",
        "赤色",
        "青色",
        "黄色",
        "緑色",
        "紫色",
        "白色",
        "黒色",
        "全部白色",
        "全部黒色"};

    static const std::vector<std::string> listInnerType{
        "TYPE 1",
        "TYPE 2",
        "TYPE 3",
        "TYPE 4",
        "TYPE 5",
        "TYPE 6",
        "TYPE 7"};

    static const std::vector<std::string> listGender{
        "男",
        "女"};

    static const std::vector<std::string> listHuntingStyle{
        "ギルドスタイル",
        "ストライカースタイル",
        "エリアルスタイル",
        "ブシドースタイル"};

    static const std::vector<std::string> listHearStyleType{
        "TYPE 1",
        "TYPE 2",
        "TYPE 3",
        "TYPE 4",
        "TYPE 5",
        "TYPE 6",
        "TYPE 7",
        "TYPE 8",
        "TYPE 9",
        "TYPE 10",
        "TYPE 11",
        "TYPE 12",
        "TYPE 13",
        "TYPE 14",
        "TYPE 15",
        "TYPE 16",
        "TYPE 17",
        "TYPE 18",
        "TYPE 19",
        "TYPE 20",
        "TYPE 21",
        "TYPE 22",
        "TYPE 23",
        "TYPE 24",
        "TYPE 25",
        "TYPE 26",
        "TYPE 27",
        "TYPE 28",
        "TYPE 29",
        "TYPE 30"};

    static const std::vector<std::string> listFaceType{
        "TYPE 1",
        "TYPE 2",
        "TYPE 3",
        "TYPE 4",
        "TYPE 5",
        "TYPE 6",
        "TYPE 7",
        "TYPE 8",
        "TYPE 9",
        "TYPE 10",
        "TYPE 11",
        "TYPE 12",
        "TYPE 13",
        "TYPE 14",
        "TYPE 15",
        "TYPE 16",
        "TYPE 17",
        "TYPE 18"};

    static const std::vector<std::string> listMakeType{
        "TYPE 1",
        "TYPE 2",
        "TYPE 3",
        "TYPE 4",
        "TYPE 5",
        "TYPE 6",
        "TYPE 7",
        "TYPE 8",
        "TYPE 9",
        "TYPE 10",
        "TYPE 11",
        "TYPE 12",
        "TYPE 13",
        "TYPE 14",
        "メイクなし"};

    static const std::vector<std::string> listChatConversion{
        "るーと √",
        "えす ∫",
        "だぶるえす ∬",
        "なんばー №",
        "けーけー ㏍",
        "てる ℡",
        "こう 爻",
        "まる(数字) ① ②",
        "ろーま(数字) Ⅰ Ⅱ",
        "(単位) ㌔ ㍍",
        "(元号) ㍻ ㍼",
        "かいぎょう",
        "たぶ",
        "どんどん追加してくよ！"};
} // namespace CTRPluginFramework

#endif